install:
  - cinst autoit.commandline

version: 1.9.alpha.{build}

build: off

test_script:
  - git submodule update --init
  - cd tests
  - autoit3 /ErrorStdOut /AutoIt3ExecuteScript suiteTest.au3 ci