version: 1.9.alpha.{build}


init:
  - Start-Job -NoNewWindow cinst autoit.commandline

build: off

test_script:
  - git submodule update --init
  - cd tests
  - autoit3 /ErrorStdOut /AutoIt3ExecuteScript suiteTest.au3 ci